name: CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  terraform:
    name: Terraform fmt, validate, plan
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Format (auto-fix)
        run: terraform fmt -check -recursive

      - name: Verify no diff after fmt
        run: git diff --exit-code

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      # Optional plan against dev.tfvars (no apply)
      - name: Terraform Plan (dev)
        run: terraform plan -var-file=dev.tfvars

  python-tests:
    name: Python Lint & Unit Tests
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: src

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r ../requirements.txt
          pip install pytest flake8

      - name: Lint with flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --max-complexity=10 --max-line-length=127 --statistics

      - name: Run unit tests
        run: pytest ../tests/unit --maxfail=1 --disable-warnings -q
